### Movies Index
GET http://localhost:3000/movies.json

### Movies Show
GET http://localhost:3000/movies/1.json

### Actor Show

GET http://localhost:3000/

### Actor Index
GET http://localhost:3000/actor.json 

### Actor Destroy

DELETE http://localhost:3000/actor/7

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Iowa Jones",
  "email": "???.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "alligators&meth&mickey@example.com",
  "password": "password"
}
